from django.conf import settings

__all__ = (
    'DS_CONFIG',
    'ENVELOPE_STATUS_CREATED',
    'ENVELOPE_STATUS_SENT',
    'ENVELOPE_STATUS_DELIVERED',
    'ENVELOPE_STATUS_SIGNED',
    'ENVELOPE_STATUS_COMPLETED',
    'ENVELOPE_STATUS_DECLINED',
    'ENVELOPE_STATUS_VOIDED',
)


DS_CONFIG = settings.DOCUSIGN

ENVELOPE_STATUS_CREATED = 'created'
ENVELOPE_STATUS_SENT = 'sent'
ENVELOPE_STATUS_DELIVERED = 'delivered'
ENVELOPE_STATUS_SIGNED = 'signed'
ENVELOPE_STATUS_COMPLETED = 'completed'
ENVELOPE_STATUS_DECLINED = 'declined'
ENVELOPE_STATUS_VOIDED = 'voided'

ENVELOPE_STATUSES = [
    ENVELOPE_STATUS_CREATED,
    ENVELOPE_STATUS_SENT,
    ENVELOPE_STATUS_DELIVERED,
    ENVELOPE_STATUS_SIGNED,
    ENVELOPE_STATUS_COMPLETED,
    ENVELOPE_STATUS_DECLINED,
    ENVELOPE_STATUS_VOIDED,
]
