apiVersion: batch/v1
kind: Job
metadata:
  name: autotests
  namespace: jlp
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 900
  activeDeadlineSeconds: 900
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: saritasa-gitlab-registry
      serviceAccountName: jlp
      nodeSelector:
        workload: job
      containers:
        - name: autotests
          image: registry.saritasa.com/jlp/backend:develop
          imagePullPolicy: Always
          env:
          - name: APP_ENV
            value: development
          - name: VAULT_SECRET
            value: https://vault.saritasa.io/v1/projects/jlp-backend-develop
          - name: TEMPLATE_PATH
            value: /home/www/app/config/settings/development.template
          command:
            - /usr/bin/run-autotests.sh
          resources:
            limits:
              cpu: 1024m
              memory: 1024Mi
            requests:
              cpu: 0m
              memory: 0Mi
