apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  namespace: jlp
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: saritasa-gitlab-registry
      serviceAccountName: jlp
      containers:
        - name: migrations
          image: registry.saritasa.com/jlp/backend:develop
          imagePullPolicy: Always
          env:
          - name: APP_ENV
            value: development
          - name: VAULT_SECRET
            value: https://vault.saritasa.io/v1/projects/jlp-backend-develop
          - name: TEMPLATE_PATH
            value: /home/www/app/config/settings/development.template
          command:
            - /usr/bin/run-migrations.sh
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 0m
              memory: 0Mi
