# Generated by Django 3.0.9 on 2020-08-21 02:35
import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import django_fsm
import model_utils.fields

import apps.core.fields.any_scheme_url
import apps.esign.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial_squashed'),
        ('users', '0001_initial_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('docusign_id', models.CharField(blank=True, help_text='Matter Attorney user GUID in DocuSign', max_length=40, null=True)),
                ('status', django_fsm.FSMField(choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('signed', 'Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('voided', 'Voided')], default='created', help_text='Envelope status from DocuSign', max_length=15)),
                ('type', models.CharField(choices=[('initial', 'Initial'), ('extra', 'Extra')], default=None, max_length=20)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='business.Matter')),
            ],
            options={
                'verbose_name': 'Envelope',
                'verbose_name_plural': 'Envelopes',
            },
        ),
        migrations.CreateModel(
            name='ESignProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='esign_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('docusign_id', models.CharField(blank=True, help_text='User GUID in DocuSign', max_length=40, null=True)),
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user ID on backend to check consent matching later', unique=True)),
                ('return_url', apps.core.fields.any_scheme_url.AnySchemeURLModelField(blank=True, editable=False, help_text='Frontend URL to which user should be returned after consent obtaining. The link location, url `scheme` should be added manually ("http://" and etc)', null=True, verbose_name='Return url')),
            ],
            options={
                'verbose_name': 'ESign Profile',
                'verbose_name_plural': 'ESign Profiles',
            },
        ),
        migrations.CreateModel(
            name='ESignDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=apps.esign.models.upload_esign_documents_to)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, help_text='Order of signing for a document within Envelope')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='esign.Envelope')),
            ],
            options={
                'verbose_name': 'ESign Document',
                'verbose_name_plural': 'ESign Documents',
            },
        ),
        migrations.AddConstraint(
            model_name='envelope',
            constraint=models.UniqueConstraint(condition=models.Q(type='initial'), fields=('matter',), name='unique_initial_envelope_for_matter'),
        ),
    ]
