IMAGEKIT_DEFAULT_FILE_STORAGE = 'apps.core.storage.SupportClosedFilesDefaultStorage'
IMAGEKIT_CACHEFILE_DIR = 'public/CACHE/images'

USER_AVATAR_SIZE = (300, 300)
NEWS_THUMBNAIL_SIZE = (300, 300)
ATTORNEY_POST_THUMBNAIL_SIZE = (300, 300)
