# Generated by Django 2.2.12 on 2020-05-14 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial_squashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QBInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qb_company_id', models.CharField(help_text='Company ID in QuickBooks (realmId)', max_length=20, verbose_name='QB company ID')),
                ('qb_invoice_id', models.IntegerField(help_text='Invoice ID in QuickBooks', verbose_name='QB Invoice ID')),
                ('qb_customer_id', models.IntegerField(help_text='Customer ID in QuickBooks', verbose_name='QB Customer ID')),
                ('invoice', models.ForeignKey(help_text='Invoice', on_delete=django.db.models.deletion.CASCADE, related_name='qb_invoices', to='business.Invoice', verbose_name='Invoice')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='qb_invoices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'QuickBooks Invoice',
                'verbose_name_plural': 'QuickBooks Invoices',
                'unique_together': {('user', 'invoice', 'qb_company_id', 'qb_invoice_id', 'qb_customer_id')},
            },
        ),
    ]
