# Generated by Django 3.0.8 on 2021-08-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_timebilling_attachment'),
        ('documents', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='documents_documents', to='business.Matter', verbose_name='Matter'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', related_query_name='documents_folders', to='business.Matter', verbose_name='Matter'),
        ),
    ]
