# Generated by Django 3.0.8 on 2021-08-23 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_folder_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(help_text='Users with which document is shared', related_name='file', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
    ]
