# Generated by Django 3.0.8 on 2021-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='seen',
            field=models.BooleanField(default=False, help_text='Seen', verbose_name='Seen'),
        ),
        migrations.AddField(
            model_name='folder',
            name='seen',
            field=models.BooleanField(default=False, help_text='Seen', verbose_name='Seen'),
        ),
    ]
