# Generated by Django 3.0.8 on 2021-09-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20210909_1752'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique root personal template folder',
        ),
    ]
