# Generated by Django 3.0.8 on 2021-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20210916_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_vault',
            field=models.BooleanField(default=False, help_text='Is in vault', verbose_name='Is in vault'),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_vault',
            field=models.BooleanField(default=False, help_text='Is in vault', verbose_name='Is in vault'),
        ),
    ]
