# Generated by Django 3.0.9 on 2020-08-21 02:11
import datetime
import uuid

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import django_fsm
import model_utils.fields

import apps.business.models.links


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0001_initial_squashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial_squashed'),
        ('forums', '0001_initial_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True, verbose_name='Lead Priority')),
                ('chat_channel', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Chat channel ID')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='users.Attorney', verbose_name='Attorney')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='users.Client', verbose_name='Client')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='forums.Topic', verbose_name='Topic')),
                ('status', django_fsm.FSMField(choices=[('active', 'Active'), ('converted', 'Converted')], default='active', max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'unique_together': {('client', 'attorney')},
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(help_text='Simple alphabetical code (identifier) of a matter', max_length=25, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Extra matter description', verbose_name='Description')),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed_amount', 'Fixed Set Amount'), ('contingency_fee', 'Contingency Fee'), ('alternative', 'Alternative Agreement')], default='hourly', max_length=25, verbose_name='Rate type')),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Amount of money taken for a rate type in $', max_digits=10, verbose_name='Rate')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('revoked', 'Revoked')], default='draft', max_length=15, verbose_name='Status')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='users.Attorney', verbose_name='Attorney')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='cities_light.City', verbose_name='City')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='users.Client', verbose_name='Client')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='cities_light.Country', verbose_name='Country')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='business.Lead', verbose_name='Lead')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='cities_light.Region', verbose_name='State')),
                ('completed', models.DateTimeField(blank=True, help_text='Datetime when the matter was completed(closed)', null=True, verbose_name='Completed datetime')),
            ],
            options={
                'verbose_name': 'Matter',
                'verbose_name_plural': 'Matters',
                'unique_together': {('attorney', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('period_start', models.DateField(help_text='Start date from which invoice money amount is calculated', verbose_name='Period start')),
                ('period_end', models.DateField(help_text='End date till which invoice money amount is calculated', verbose_name='Period end')),
                ('title', models.CharField(help_text='Title which describes current invoice', max_length=255, verbose_name='Title')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='business.Matter')),
                ('note', models.TextField(blank=True, help_text='A note left by attorney', null=True, verbose_name='Note')),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', help_text='Status of invoice', max_length=30, verbose_name='Status')),
                ('payment', models.OneToOneField(blank=True, help_text='Link to payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', related_query_name='business_invoice', to='finance.Payment', verbose_name='Payment')),
                ('payment_status', django_fsm.FSMField(choices=[('not_started', 'Not started'), ('payment_in_progress', 'Payment in progress'), ('payment_failed', 'Payment failed'), ('paid', 'Paid')], default='not_started', help_text='Status of payment', max_length=30, verbose_name='Payment Status')),
                ('created_by', models.ForeignKey(editable=False, help_text='AppUser that created invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='users.Attorney', verbose_name='Attorney')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.AddField(
            model_name='matter',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='business.Stage', verbose_name='Stage'),
        ),
        migrations.CreateModel(
            name='ChecklistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(help_text='Description of checklist', verbose_name='Description')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist', to='users.Attorney', verbose_name='Attorney')),
            ],
            options={
                'verbose_name': 'Checklist Entry',
                'verbose_name_plural': 'Checklist Entries',
                'unique_together': {('attorney', 'description')},
            },
        ),
        migrations.CreateModel(
            name='TimeBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(help_text='Full description of made work', verbose_name='Description')),
                ('time_spent', models.DurationField(help_text='Amount of time that attorney spent on this work', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=900)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))], verbose_name='Time Spent')),
                ('fees', models.DecimalField(decimal_places=2, default=0, help_text='Amount of money should be paid for a spent time', max_digits=10, verbose_name='Fees')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billed_time', to='business.Matter', verbose_name='Matter')),
                ('date', models.DateField(help_text='Date in which billed work was made', verbose_name='Date')),
                ('created_by', models.ForeignKey(editable=False, help_text='AppUser created time billing', on_delete=django.db.models.deletion.PROTECT, related_name='billed_time', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Time Billing',
                'verbose_name_plural': 'Time Billings',
            },
        ),
        migrations.CreateModel(
            name='MatterPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(verbose_name='Text of the post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Matter Message Post',
                'verbose_name_plural': 'Matter Message Posts',
            },
        ),
        migrations.CreateModel(
            name='MatterTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('post_count', models.IntegerField(default=0, verbose_name='Post count')),
                ('last_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_in_topic', to='business.MatterPost', verbose_name='Last post')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='business.Matter')),
            ],
            options={
                'verbose_name': 'Matter Message Topic',
                'verbose_name_plural': 'Matter Message Topics',
            },
        ),
        migrations.AddField(
            model_name='matterpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='business.MatterTopic', verbose_name='Topic'),
        ),
        migrations.CreateModel(
            name='TimeBillingAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_time_billing', to='business.Invoice', verbose_name='Invoice')),
                ('time_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_invoice', to='business.TimeBilling', verbose_name='Time Billing')),
            ],
            options={
                'verbose_name': 'Attached Time Billing',
                'verbose_name_plural': 'Attached Time Billings',
                'unique_together': {('time_billing', 'invoice')},
            },
        ),
        migrations.AddField(
            model_name='timebilling',
            name='invoices',
            field=models.ManyToManyField(related_name='time_billing', through='business.TimeBillingAttachment', to='business.Invoice', verbose_name='Invoices'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_by', models.ForeignKey(help_text='AppUser created the note', on_delete=django.db.models.deletion.PROTECT, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='business.Matter')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id of call(name of room in jitsi)', unique=True, verbose_name='Id of call')),
                ('participants', models.ManyToManyField(related_name='video_calls', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Video Call',
                'verbose_name_plural': 'Video Calls',
            },
        ),
        migrations.CreateModel(
            name='MatterSharedWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('matter', models.ForeignKey(help_text='Matter that was shared with attorney', on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='business.Matter', verbose_name='Matter')),
                ('user', models.ForeignKey(help_text='User with which matter was shared', on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Matter Shared With',
                'verbose_name_plural': 'Matters Shared With',
                'unique_together': {('matter', 'user')},
            },
        ),
        migrations.AddField(
            model_name='matter',
            name='shared_with',
            field=models.ManyToManyField(help_text='Users with which matter is shared', related_name='shared_matters', through='business.MatterSharedWith', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Title which describes current activity', max_length=255, verbose_name='Title')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='business.Matter')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='VoiceConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(help_text="Voice consent's file", max_length=255, upload_to=apps.business.models.links.upload_voice_consents_to, verbose_name='File')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_consents', to='business.Matter')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Voice Consent',
                'verbose_name_plural': 'Voice Consents',
                'unique_together': {('matter', 'title')},
            },
        ),
    ]
