# Generated by Django 3.0.8 on 2021-06-15 16:04

import apps.business.models.matter
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210518_2030'),
        ('business', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Currencies', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='matter',
            name='fee_note',
            field=models.CharField(default='', max_length=255, verbose_name='Fee note'),
        ),
        migrations.AddField(
            model_name='matter',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.FeeKind', verbose_name='Fee type'),
        ),
        migrations.AddField(
            model_name='matter',
            name='is_billable',
            field=models.BooleanField(default=False, verbose_name='Is billable'),
        ),
        migrations.AddField(
            model_name='matter',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Speciality', verbose_name='Speciality'),
        ),
        migrations.AddField(
            model_name='matter',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='code',
            field=models.CharField(default=apps.business.models.matter.create_matter_code, help_text='Simple alphabetical code (identifier) of a matter', max_length=25, verbose_name='Code'),
        ),
    ]
