# Generated by Django 3.0.8 on 2021-06-24 20:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210611_1424'),
        ('business', '0002_auto_20210615_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created'
                    )
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified'
                    )
                ),
                (
                    'chat_channel',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name='Chat channel ID'
                    )
                ),
                (
                    'priority',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('high', 'High'),
                            ('medium', 'Medium'),
                            ('low', 'Low')
                        ],
                        max_length=10,
                        null=True,
                        verbose_name='Opportunity Priority'
                    )
                ),
                (
                    'attorney',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='opportunities',
                        to='users.Attorney',
                        verbose_name='Attorney'
                    )
                ),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='opportunities',
                        to='users.Client',
                        verbose_name='Client'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
