# Generated by Django 3.0.8 on 2021-06-30 20:15

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebilling',
            name='billing_type',
            field=models.CharField(
                choices=[
                    ('expense', 'Expense'),
                    ('time', 'Time')],
                default='time',
                max_length=10,
                verbose_name='Billing Type'
            ),
        ),
        migrations.AlterField(
            model_name='timebilling',
            name='time_spent',
            field=models.DurationField(
                blank=True,
                help_text='Amount of time that attorney spent on this work',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(
                            seconds=900
                        )
                    ),
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(
                            days=1
                        )
                    )
                ],
                verbose_name='Time Spent'
            ),
        ),
    ]
