# Generated by Django 3.0.8 on 2021-07-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20210630_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(
                blank=True,
                help_text='The date on which payment for this invoice is due.',
                null=True,
                verbose_name='Due Date'
            ),
        ),
    ]
