# Generated by Django 3.0.8 on 2021-07-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210623_1218'),
        ('business', '0005_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='invite',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='matters',
                to='users.Invite',
                verbose_name='Invite'
            ),
        ),
        migrations.AlterField(
            model_name='matter',
            name='client',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='matters',
                to='users.Client',
                verbose_name='Client'
            ),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('client__isnull', False),
                    ('invite__isnull', False),
                    _connector='OR'),
                name='One of the client or invite should not be null'
            ),
        ),
    ]
