# Generated by Django 3.0.8 on 2021-07-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20210706_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='fee_note',
        ),
    ]
