# Generated by Django 3.0.8 on 2021-07-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forums', '0001_initial_squashed'),
        ('business', '0007_remove_matter_fee_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='topic',
        ),
        migrations.AddField(
            model_name='lead',
            name='post',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='leads', to='forums.Post',
                verbose_name='Post'),
        ),
    ]
