# Generated by Django 3.0.8 on 2021-08-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20210727_0944'),
        ('business', '0008_auto_20210728_2157'),
        ('business', '0008_auto_20210727_1853'),
    ]

    operations = [
    ]
