# Generated by Django 3.0.8 on 2021-08-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0041_auto_20210803_1231'),
        ('business', '0009_merge_20210803_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(verbose_name='Text of the post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Matter Message Comment',
                'verbose_name_plural': 'Matter Message Comments',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(blank=True, help_text='Referral message', null=True, verbose_name='Message')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral', to='users.Attorney', verbose_name='Attorney')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.RemoveField(
            model_name='matterpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='matterpost',
            name='text',
        ),
        migrations.RemoveField(
            model_name='matterpost',
            name='topic',
        ),
        migrations.AddField(
            model_name='matterpost',
            name='attachments',
            field=models.ManyToManyField(related_name='matter_topic', to='business.Attachment', verbose_name='Attachments'),
        ),
        migrations.AddField(
            model_name='matterpost',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='Comment count'),
        ),
        migrations.AddField(
            model_name='matterpost',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='business.Matter'),
        ),
        migrations.AddField(
            model_name='matterpost',
            name='participants',
            field=models.ManyToManyField(related_name='matter_topic', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='matterpost',
            name='seen',
            field=models.BooleanField(default=False, help_text='If the matter topic has been read or not', verbose_name='Seen'),
        ),
        migrations.AddField(
            model_name='matterpost',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='status',
            field=django_fsm.FSMField(choices=[('open', 'Open'), ('referral', 'Referral'), ('close', 'Close')], default='open', max_length=15, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='MatterTopic',
        ),
        migrations.AddField(
            model_name='mattercomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='business.MatterPost', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='matter',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='business.Referral', verbose_name='Referral'),
        ),
        migrations.AddField(
            model_name='matterpost',
            name='last_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_comment_on_post', to='business.MatterComment', verbose_name='Last Comment'),
        ),
    ]
