# Generated by Django 3.0.8 on 2021-08-03 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210803_1231'),
        ('business', '0010_auto_20210803_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedMatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budget Min')),
                ('budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budget Max')),
                ('budget_type', models.CharField(choices=[('hourly', 'Hourly'), ('flat_fee', 'Flat Fee'), ('contingency_fee', 'Contingency Fee'), ('other', 'Other Fee')], default='hourly', max_length=25, verbose_name='Budget type')),
                ('description', models.TextField(help_text='Extra matter description', verbose_name='Description')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_matters', to='users.Client', verbose_name='Client')),
                ('practice_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_matter', to='users.Speciality', verbose_name='Related practice area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rate')),
                ('description', models.TextField(help_text='Proposal description', verbose_name='Description')),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('chat', 'Chat')], default='pending', max_length=15, verbose_name='Status')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='users.Attorney', verbose_name='Attorney')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposals', to='business.PostedMatter', verbose_name='Posted Matter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
