# Generated by Django 3.0.8 on 2021-08-04 21:26

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0011_postedmatter_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='rate_type',
            field=models.CharField(
                choices=[('hourly', 'Hourly'), ('flat_fee', 'Flat Fee'),
                         ('contingency_fee', 'Contingency Fee'),
                         ('other', 'Other Fee')], default='hourly',
                max_length=25, verbose_name='Rate type'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=django_fsm.FSMField(
                choices=[('pending', 'Pending'), ('accepted', 'Accepted'),
                         ('revoked', 'Revoked'), ('chat', 'Chat'),
                         ('withdrawn', 'withdrawn')], default='pending',
                max_length=15, verbose_name='Status'),
        ),
    ]
