# Generated by Django 3.0.8 on 2021-08-11 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0042_speciality_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0012_auto_20210804_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebilling',
            name='billed_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='billing_item',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Billed by'),
        ),
        migrations.AddField(
            model_name='timebilling',
            name='client',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='billed_item',
                to='users.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='timebilling',
            name='currency',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='users.Currencies',
                verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='timebilling',
            name='hourly_rate',
            field=models.DecimalField(
                decimal_places=2, default=0,
                help_text='Hourly rate for which time entry is added',
                max_digits=10,
                verbose_name='Hourly rate'),
        ),
        migrations.AddField(
            model_name='timebilling',
            name='is_billable',
            field=models.BooleanField(default=False,
                                      verbose_name='Is billable entry'),
        ),
    ]
