# Generated by Django 3.0.8 on 2021-08-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210804_2243'),
        ('business', '0014_auto_20210813_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attorney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.Attorney', verbose_name='Attorney'),
        ),
    ]
