# Generated by Django 3.0.8 on 2021-08-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20210812_2218'),
        ('business', '0015_auto_20210813_1738'),
    ]

    operations = [
    ]
