# Generated by Django 3.0.8 on 2021-08-14 22:02

from django.db import migrations, models

import apps.documents.models.resources


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0016_merge_20210813_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebilling',
            name='attachment',
            field=models.FileField(
               blank=True, help_text="Document's file",
               max_length=255, null=True,
               upload_to=apps.documents.models.resources.upload_documents_to,
               verbose_name='File'),
        ),
    ]
