# Generated by Django 3.0.8 on 2021-08-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210804_2243'),
        ('business', '0016_merge_20210813_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_items',
            field=models.ManyToManyField(related_name='invoices_billing_items', to='business.TimeBilling', verbose_name='billing_items'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Invoice Email'),
        ),
    ]
