# Generated by Django 3.0.8 on 2021-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20210814_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_days',
            field=models.IntegerField(blank=True, help_text='The days on which payment for this invoice is due.', null=True, verbose_name='Due days'),
        ),
    ]
