# Generated by Django 3.0.8 on 2021-08-18 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0017_timebilling_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('start_time',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      verbose_name='Start time')),
                ('end_time',
                 models.DateTimeField(null=True, verbose_name='End time')),
                ('billing_item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='time_entries',
                                   to='business.TimeBilling',
                                   verbose_name='Billing Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
