# Generated by Django 3.0.8 on 2021-08-14 23:12

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_invoice_due_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=django_fsm.FSMField(choices=[('overdue', 'Overdue'), ('open', 'Open'), ('paid', 'Paid'), ('voided', 'Voided'), ('draft', 'Draft')], default='draft', help_text='Status of invoice', max_length=30, verbose_name='Status'),
        ),
    ]
