# Generated by Django 3.0.8 on 2021-08-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20210814_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Direct Debit(ACH/echeck)', 'Direct Debit(ACH/echeck)'), ('Credit Cards', 'Credit Cards')], default='Credit Cards', max_length=30, verbose_name='PaymentMethod'),
        ),
    ]
