# Generated by Django 3.0.8 on 2021-08-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_invoice_payment_method'),
        ('business', '0017_timebilling_attachment'),
    ]

    operations = [
    ]
