# Generated by Django 3.0.8 on 2021-08-16 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_merge_20210816_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key of invitation, used to make unique invitation link', verbose_name='UUID'),
        ),
    ]
