# Generated by Django 3.0.8 on 2021-08-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_mattercomment_seen'),
        ('business', '0024_auto_20210816_1913'),
    ]

    operations = [
    ]
