# Generated by Django 3.0.8 on 2021-08-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_timeentry'),
        ('business', '0026_auto_20210818_0031'),
    ]

    operations = [
    ]
