# Generated by Django 3.0.8 on 2021-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_matter_fee_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=15, null=True, verbose_name='Invoice Number'),
        ),
    ]
