# Generated by Django 3.0.8 on 2021-08-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_matter_fee_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='business.Matter'),
        ),
        migrations.AlterField(
            model_name='matterpost',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='business.Matter'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='business.Matter'),
        ),
        migrations.AlterField(
            model_name='timebilling',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billed_time', to='business.Matter', verbose_name='Matter'),
        ),
        migrations.AlterField(
            model_name='voiceconsent',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_consents', to='business.Matter'),
        ),
    ]
