# Generated by Django 3.0.8 on 2021-08-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forums', '0003_auto_20210818_1825'),
        ('business', '0030_auto_20210820_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedmatter',
            name='practice_area',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='posted_matter',
                to='forums.ForumPracticeAreas',
                verbose_name='Related practice area'),
        ),
    ]
