# Generated by Django 3.0.8 on 2021-08-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0030_auto_20210820_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
