# Generated by Django 3.0.8 on 2021-08-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_auto_20210824_2015'),
        ('business', '0031_note_client'),
    ]

    operations = [
    ]
