# Generated by Django 3.0.8 on 2021-08-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20210819_1408'),
        ('business', '0032_merge_20210824_2244'),
    ]

    operations = [
    ]
