# Generated by Django 3.0.8 on 2021-08-25 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_merge_20210825_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='finalized',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalized Date'),
        ),
        migrations.CreateModel(
            name='InvoiceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Title which describes current activity', max_length=255, verbose_name='Title')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='business.Invoice')),
            ],
            options={
                'verbose_name': 'InvoiceActivity',
                'verbose_name_plural': 'InvoiceActivities',
            },
        ),
    ]
