# Generated by Django 3.0.8 on 2021-08-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20210827_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='activities',
            field=models.ManyToManyField(related_name='invoices', to='business.InvoiceActivity', verbose_name='activities'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='logs',
            field=models.ManyToManyField(related_name='invoices', to='business.InvoiceLog', verbose_name='logs'),
        ),
    ]
