# Generated by Django 3.0.8 on 2021-08-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_auto_20210826_1802'),
        ('business', '0035_auto_20210826_0239'),
    ]

    operations = [
    ]
