# Generated by Django 3.0.8 on 2021-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_auto_20210827_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelog',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='Status code'),
        ),
    ]
