# Generated by Django 3.0.8 on 2021-08-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_invoicelog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelog',
            old_name='logs',
            new_name='log',
        ),
    ]
