# Generated by Django 3.0.8 on 2021-09-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_auto_20210827_1720'),
        ('business', '0036_merge_20210827_1523'),
    ]

    operations = [
    ]
