# Generated by Django 3.0.8 on 2021-09-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_merge_20210902_0022'),
        ('business', '0041_remove_matter_rate_type'),
    ]

    operations = [
    ]
