# Generated by Django 3.0.8 on 2021-09-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_merge_20210902_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattercomment',
            name='seen_by_client',
            field=models.BooleanField(default=False, help_text='If the matter topic has been read or not by client', verbose_name='Seen'),
        ),
        migrations.AddField(
            model_name='matterpost',
            name='seen_by_client',
            field=models.BooleanField(default=False, help_text='If the matter topic has been read or not by client', verbose_name='Seen'),
        ),
    ]
