# Generated by Django 3.0.8 on 2021-09-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_auto_20210909_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of money taken for a rate type in $', max_digits=30, verbose_name='Rate'),
        ),
    ]
