# Generated by Django 3.0.8 on 2021-09-13 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_auto_20210913_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status_modified',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='Datetime when status was modified',
                verbose_name='Status Modified'
            ),
        ),
    ]
