# Generated by Django 3.0.8 on 2021-09-20 18:31

import django.utils.timezone
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0045_proposal_status_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedmatter',
            name='status',
            field=django_fsm.FSMField(
                choices=[
                    ('active', 'Active'),
                    ('inactive', 'Inactive')],
                default='active',
                max_length=15,
                verbose_name='Status'
            ),
        ),
        migrations.AddField(
            model_name='postedmatter',
            name='status_modified',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='Datetime when status was modified',
                verbose_name='Status Modified'
            ),
        ),
    ]
