# Generated by Django 3.0.8 on 2021-10-01 15:33

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0048_matter_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('chat', 'Chat'), ('withdrawn', 'withdrawn'), ('closed by client', 'closed by client')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
