# Generated by Django 3.0.8 on 2021-10-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20211007_0912'),
        ('business', '0049_auto_20211001_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.Enterprise', verbose_name='Enterprises'),
        ),
        migrations.AddField(
            model_name='lead',
            name='paralegal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.Paralegal', verbose_name='Paralegal'),
        ),
    ]
