# Generated by Django 3.0.8 on 2021-10-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0050_auto_20211007_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='rate_detail',
            field=models.TextField(blank=True, help_text='Rate description', null=True, verbose_name='Rate description'),
        ),
    ]
