# Generated by Django 3.0.8 on 2021-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0051_proposal_rate_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedmatter',
            name='budget_detail',
            field=models.TextField(blank=True, help_text='Budget description', null=True, verbose_name='Budget description'),
        ),
    ]
