# Generated by Django 3.0.14 on 2021-10-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_remove_invite_job'),
        ('business', '0052_postedmatter_budget_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posted_matters', to='users.Currencies', verbose_name='Currency'),
        ),
    ]
