# Generated by Django 3.0.14 on 2021-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0057_auto_20211111_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedmatter',
            name='budget_max',
            field=models.CharField(max_length=50, verbose_name='Budget Max'),
        ),
    ]
