# Generated by Django 3.0.14 on 2021-11-12 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0058_auto_20211111_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattercomment',
            name='participants',
            field=models.ManyToManyField(related_name='matter_comments_pariticipants', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
