# Generated by Django 3.0.14 on 2021-11-30 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0060_mattercomment_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattercomment',
            name='deleted_participants',
            field=models.ManyToManyField(related_name='matter_comments_deleted_pariticipants', to=settings.AUTH_USER_MODEL, verbose_name='Deleted Participants'),
        ),
    ]
