# Generated by Django 3.0.14 on 2021-12-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0062_auto_20211220_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timebilling',
            name='attachment',
        ),
        migrations.AddField(
            model_name='timebilling',
            name='attachments',
            field=models.ManyToManyField(help_text='Billing item attachments', to='business.Attachment', verbose_name='File'),
        ),
    ]
