# Generated by Django 3.0.14 on 2021-12-20 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0063_appuser_onboarding'),
        ('business', '0063_auto_20211220_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeBilling',
            new_name='BillingItem',
        ),
    ]
