# Generated by Django 3.0.14 on 2021-12-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0064_auto_20211220_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeBillingAttachment',
            new_name='BillingItemAttachment',
        ),
    ]
