# Generated by Django 3.0.14 on 2021-12-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_appuser_onboarding'),
        ('business', '0065_auto_20211220_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedmatter',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posted_matters', to='users.Currencies', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='users.Currencies', verbose_name='Currency'),
        ),
    ]
