# Generated by Django 3.0.14 on 2022-01-05 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0066_auto_20211220_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='billed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billed_item', to=settings.AUTH_USER_MODEL, verbose_name='Billed by'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text='AppUser created time billing', on_delete=django.db.models.deletion.PROTECT, related_name='billing_item', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_item', to='business.Matter', verbose_name='Matter'),
        ),
    ]
