# Generated by Django 3.0.14 on 2022-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0067_auto_20220105_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedmatter',
            name='is_hidden_for_attorney',
            field=models.BooleanField(default=False, verbose_name='Hidden for attorney'),
        ),
        migrations.AddField(
            model_name='postedmatter',
            name='is_hidden_for_client',
            field=models.BooleanField(default=False, verbose_name='Hidden for client'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_hidden_for_attorney',
            field=models.BooleanField(default=False, verbose_name='Hidden for attorney'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_hidden_for_client',
            field=models.BooleanField(default=False, verbose_name='Hidden for client'),
        ),
    ]
