# Generated by Django 3.0.14 on 2022-01-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0068_auto_20220110_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingitemattachment',
            unique_together=set(),
        ),
    ]
