# Generated by Django 3.0.14 on 2022-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0069_auto_20220124_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate', max_digits=10, verbose_name='Tax rate'),
        ),
    ]
