# Generated by Django 3.0.14 on 2022-01-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0072_auto_20220125_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
