# Generated by Django 3.0.14 on 2022-02-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0073_auto_20220126_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingitem',
            options={'verbose_name': 'Billing Item', 'verbose_name_plural': 'Billing Item'},
        ),
    ]
