# Generated by Django 3.0.14 on 2022-02-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_speciality_created_by'),
        ('business', '0075_auto_20220223_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedmatter',
            name='practice_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_matter', to='users.Speciality', verbose_name='Related practice area'),
        ),
    ]
