# Generated by Django 3.0.14 on 2022-03-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20220211_1650'),
        ('business', '0076_auto_20220224_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedmatter',
            name='practice_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_matter', to='forums.ForumPracticeAreas', verbose_name='Related practice area'),
        ),
    ]
