# Generated by Django 3.0.14 on 2022-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0077_auto_20220301_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('message', 'Message'), ('document', 'Document'), ('note', 'Note'), ('billing_item', 'Billing Item'), ('invoice', 'Invoice')], default=None, max_length=25, null=True, verbose_name='Activity type'),
        ),
    ]
