# Generated by Django 3.0.14 on 2022-03-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0079_update_existing_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('message', 'Message'), ('document', 'Document'), ('note', 'Note'), ('invoice', 'Invoice')], default=None, max_length=25, null=True, verbose_name='Activity type'),
        ),
    ]
