# Generated by Django 3.0.14 on 2022-03-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0080_auto_20220316_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount for which expense entry is added', max_digits=10, verbose_name='Total amount'),
        ),
    ]
