# Generated by Django 3.0.14 on 2022-03-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0083_auto_20220318_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_days',
            field=models.IntegerField(default=0, help_text='The days on which payment for this invoice is due.', verbose_name='Due days'),
        ),
    ]
