# Generated by Django 3.0.14 on 2022-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0084_auto_20220321_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('message', 'Message'), ('document', 'Document'), ('note', 'Note'), ('invoice', 'Invoice'), ('billing_item', 'Billing item')], default=None, max_length=25, null=True, verbose_name='Activity type'),
        ),
    ]
