# Generated by Django 3.0.14 on 2022-03-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0085_auto_20220322_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_items',
            field=models.ManyToManyField(related_name='billing_items_invoices', to='business.BillingItem', verbose_name='billing_items'),
        ),
    ]
