# Generated by Django 3.0.14 on 2022-04-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0087_opportunity_paralegal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='enterprise',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
