# Generated by Django 3.0.14 on 2022-04-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20220428_0608'),
        ('business', '0088_auto_20220428_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.Enterprise', verbose_name='Enterprises'),
        ),
    ]
