# Generated by Django 3.0.8 on 2021-04-27 19:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_squashed_0035_auto_20200819_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How much attorney take per hour', max_digits=10, verbose_name='Fee rate'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='firm_location',
            field=django.contrib.gis.db.models.fields.PointField(help_text="Attorney's location coordinates", null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='firm_location_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='All information about location from Google stored as JSON', null=True, verbose_name='Location data'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='How long has attorney been practicing'),
        ),
    ]
