# Generated by Django 3.0.8 on 2021-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0006_auto_20210505_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='practice_jurisdictions',
            field=models.ManyToManyField(help_text='State(s) or federal jurisdiction attorney are licensed or authorised to practice in', related_name='attorneys', to='cities_light.Region', verbose_name='Practice jurisdictions'),
        ),
    ]
