# Generated by Django 3.0.8 on 2021-05-05 15:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210505_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('agency', models.CharField(max_length=100, unique=True, verbose_name='Agency')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agency',
            },
        ),
        migrations.AddField(
            model_name='attorney',
            name='practice_jurisdictions_agency',
            field=models.ManyToManyField(help_text='agency information of jurisdiction attorney', related_name='attorneys', to='users.Agency', verbose_name='Practice jurisdictions agency'),
        ),
    ]
