# Generated by Django 3.0.8 on 2021-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210505_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency',
            field=models.CharField(max_length=100, verbose_name='Agency'),
        ),
    ]
