# Generated by Django 3.0.8 on 2021-05-06 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0009_auto_20210505_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('agency', models.CharField(max_length=100, verbose_name='Agency')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurisdiction', to='cities_light.Country', verbose_name='Jurisdiction country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurisdiction', to='cities_light.Region', verbose_name='Jurisdiction state')),
            ],
            options={
                'verbose_name': 'Jurisdiction',
                'verbose_name_plural': 'Jurisdiction',
            },
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='practice_jurisdictions_agency',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='practice_jurisdictions_country',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.AlterField(
            model_name='attorney',
            name='practice_jurisdictions',
            field=models.ManyToManyField(help_text='Country, State(s), Agency(s) or federal jurisdiction attorney are licensed or authorised to practice in', related_name='attorneys', to='users.Jurisdiction', verbose_name='Practice jurisdictions'),
        ),
    ]
