# Generated by Django 3.0.8 on 2021-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210506_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, help_text="Client's location(address1)", max_length=50, null=True, verbose_name='Address1'),
        ),
        migrations.AddField(
            model_name='client',
            name='address2',
            field=models.CharField(blank=True, help_text="Client's location(address2)", max_length=50, null=True, verbose_name='Address2'),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, help_text="Client's location(zip code)", max_length=10, null=True, verbose_name='zip code'),
        ),
    ]
