# Generated by Django 3.0.8 on 2021-05-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='fee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attorneys', to='users.Currencies', verbose_name='Fee Currency'),
        ),
    ]
