# Generated by Django 3.0.8 on 2021-05-17 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0014_attorney_fee_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='firm_location',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='firm_location_city',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='firm_location_data',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='firm_location_state',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='firm_place_id',
        ),
        migrations.CreateModel(
            name='FirmLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZipCode')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_location', to='cities_light.Country', verbose_name='Firm country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_location', to='cities_light.Region', verbose_name='Firm state')),
            ],
            options={
                'verbose_name': 'FirmLocation',
                'verbose_name_plural': 'FirmLocation',
            },
        ),
        migrations.AddField(
            model_name='attorney',
            name='firm_locations',
            field=models.ManyToManyField(help_text="Country, State(s), Address(s), City(s), Zipcode of attorney's Firm", related_name='attorneys', to='users.FirmLocation', verbose_name='Firm Location'),
        ),
    ]
