# Generated by Django 3.0.8 on 2021-05-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210517_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethod',
            new_name='PaymentType',
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Payment Type', 'verbose_name_plural': 'Payment Type'},
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='attorney',
            name='payment_type',
            field=models.ManyToManyField(related_name='attorneys', to='users.PaymentType', verbose_name='PaymentType'),
        ),
    ]
