# Generated by Django 3.0.8 on 2021-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210518_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='Registeration number'),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='year',
            field=models.CharField(max_length=4, null=True, verbose_name='Admitted year'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='agency',
            field=models.CharField(max_length=100, null=True, verbose_name='Agency'),
        ),
    ]
