# Generated by Django 3.0.8 on 2021-05-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210525_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='biography',
            field=models.TextField(blank=True, help_text="Attorney's legal pratice", null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='attorney',
            name='firm_name',
            field=models.CharField(help_text='Firm Name', max_length=100, null=True, verbose_name='Firm name'),
        ),
        migrations.AddField(
            model_name='attorney',
            name='website',
            field=models.URLField(blank=True, help_text='Firm website url', null=True, verbose_name='Firm website'),
        ),
    ]
