# Generated by Django 3.0.8 on 2021-05-25 22:44

import apps.users.models.users
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210525_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='is_submittable_potential',
            field=models.BooleanField(default=False, help_text='Sumbit proposals for potential client engagments', verbose_name='Is Submittable Potential'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.users.models.users.upload_user_avatar_to),
        ),
    ]
