# Generated by Django 3.0.8 on 2021-05-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210525_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attorney',
            old_name='fee_kinds',
            new_name='fee_types',
        ),
    ]
