# Generated by Django 3.0.8 on 2021-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210526_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text="Client's phone number", max_length=128, null=True, verbose_name='Phone'),
        ),
    ]
