# Generated by Django 3.0.8 on 2021-05-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_client_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='is_disciplined',
        ),
    ]
