# Generated by Django 3.0.8 on 2021-06-09 16:35

import apps.users.models.users
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('verification_status', django_fsm.FSMField(choices=[('not_verified', 'Not verified'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_verified', max_length=20, verbose_name='Verification_status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='enterprise', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('role', models.CharField(help_text='Enterprise Role', max_length=20, verbose_name='Enterprise Role')),
                ('phone', models.CharField(help_text="Enterprise's phone number", max_length=128, verbose_name='Phone')),
                ('featured', models.BooleanField(default=False, verbose_name='Is featured')),
                ('firm_name', models.CharField(help_text='Firm Name', max_length=100, null=True, verbose_name='Firm name')),
                ('firm_size', models.IntegerField(help_text='Firm size', verbose_name='Firm size')),
                ('firm_locations', models.ManyToManyField(help_text="Country, State(s), Address(s), City(s), Zipcode of enterprise's Firm", related_name='enterprise', to='users.FirmLocation', verbose_name='Firm Location')),
                ('followers', models.ManyToManyField(related_name='followed_enterprise', to=settings.AUTH_USER_MODEL, verbose_name='Followers')),
                ('team_members', models.ManyToManyField(help_text='Email, User type of enterprise members', related_name='enterprise', to='users.Member', verbose_name='Team Members')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprise',
            },
            bases=(apps.users.models.users.AppUserHelperMixin, models.Model),
        ),
    ]
