# Generated by Django 3.0.8 on 2021-06-11 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='Firmsize')),
            ],
            options={
                'verbose_name': 'Firmsize',
                'verbose_name_plural': 'Firmsize',
            },
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='firm_size',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='firm_sizes',
            field=models.ForeignKey(blank=True, help_text='Firm size', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise', to='users.FirmSize', verbose_name='Firm size'),
        ),
    ]
