# Generated by Django 3.0.8 on 2021-06-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210611_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='firm_sizes',
            new_name='firm_size',
        ),
    ]
