# Generated by Django 3.0.8 on 2021-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210611_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('attorney', 'Attorney'), ('paralegal', 'Paralegal')], default='attorney', max_length=10, verbose_name='Type of member'),
        ),
    ]
