# Generated by Django 3.0.8 on 2021-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210623_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='firm_name',
            field=models.CharField(blank=True, help_text='Firm Name', max_length=100, null=True, verbose_name='Firm name'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='firm_name',
            field=models.CharField(blank=True, help_text='Firm Name', max_length=100, null=True, verbose_name='Firm name'),
        ),
        migrations.AlterField(
            model_name='paralegal',
            name='firm_name',
            field=models.CharField(blank=True, help_text='Firm Name', max_length=100, null=True, verbose_name='Firm name'),
        ),
    ]
