# Generated by Django 3.0.8 on 2021-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210709_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='spoken_language',
            field=models.ManyToManyField(blank=True, related_name='attorneys', to='users.Language', verbose_name='SpokenLanguages'),
        ),
        migrations.AlterField(
            model_name='paralegal',
            name='spoken_language',
            field=models.ManyToManyField(blank=True, related_name='paralegals', to='users.Language', verbose_name='SpokenLanguages'),
        ),
    ]
