# Generated by Django 3.0.8 on 2021-07-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210713_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle name'),
        ),
    ]
