# Generated by Django 3.0.8 on 2021-07-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0036_appuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='address',
            field=models.CharField(
                blank=True,
                help_text="Invited contact's location(address1)",
                max_length=100,
                null=True,
                verbose_name='Address1'
            ),
        ),
        migrations.AddField(
            model_name='invite',
            name='city',
            field=models.CharField(
                blank=True,
                help_text="Invited contact's city",
                max_length=50,
                null=True,
                verbose_name='City'
            ),
        ),
        migrations.AddField(
            model_name='invite',
            name='country',
            field=models.ForeignKey(
                blank=True,
                help_text="Invited contact's country",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contacts_country',
                to='cities_light.Country',
                verbose_name='Country'
            ),
        ),
        migrations.AddField(
            model_name='invite',
            name='middle_name',
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name='Middle name'
            ),
        ),
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.CharField(
                blank=True,
                help_text="Invited contact's job title",
                max_length=128,
                null=True,
                verbose_name='role'
            ),
        ),
        migrations.AddField(
            model_name='invite',
            name='state',
            field=models.ForeignKey(
                blank=True,
                help_text="Invited contact's state",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contacts_state',
                to='cities_light.Region',
                verbose_name='State'
            ),
        ),
        migrations.AddField(
            model_name='invite',
            name='zip_code',
            field=models.CharField(
                blank=True,
                help_text="Invited contact's location(zip code)",
                max_length=10,
                null=True,
                verbose_name='zip code'
            ),
        ),
        migrations.AlterField(
            model_name='invite',
            name='message',
            field=models.TextField(
                blank=True,
                help_text='Message of invitation',
                null=True,
                verbose_name='Message'
            ),
        ),
    ]
