# Generated by Django 3.0.8 on 2021-07-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210715_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Designates whether the user subscribe email notification', verbose_name='Subscribed'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, help_text='Used to make unique user unsubscribe link', verbose_name='User uuid'),
        ),
    ]
