# Generated by Django 3.0.8 on 2021-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210715_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='client_type',
            field=models.CharField(
                choices=[
                    ('client', 'Client'),
                    ('lead', 'Lead')
                ],
                help_text='Type of invitee',
                max_length=50,
                verbose_name='Type of invitee'
            ),
        ),
    ]
