# Generated by Django 3.0.8 on 2021-07-23 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_create_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used to make unique user unsubscribe link', unique=True, verbose_name='User uuid'),
        ),
    ]
