# Generated by Django 3.0.8 on 2021-08-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210723_1758'),
        ('users', '0038_auto_20210723_1225'),
    ]

    operations = [
    ]
