# Generated by Django 3.0.8 on 2021-08-03 12:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_merge_20210803_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.TextField(verbose_name='Timezone')),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
            },
        ),
        migrations.AddField(
            model_name='attorney',
            name='contacted_clients',
            field=models.ManyToManyField(help_text='List of contacted client', related_name='attorney', to='users.Client', verbose_name='Contacted Client'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='tag',
            field=models.CharField(choices=[('opportunities', 'Opportunities'), ('open_matter', 'Open matter'), ('referred_matter', 'Referred matter'), ('close_matter', 'Close matter'), ('active_lead', 'Active lead'), ('converted_lead', 'Converted lead')], help_text='Identifier of statistic', max_length=50, verbose_name='Tag'),
        ),
    ]
