# Generated by Django 3.0.8 on 2021-08-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0041_auto_20210803_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Description'),
        ),
    ]
