# Generated by Django 3.0.8 on 2021-08-25 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210816_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Inviter'),
        ),
    ]
