# Generated by Django 3.0.8 on 2021-08-29 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20210825_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shared_with',
            field=models.ManyToManyField(help_text='Users with which client is shared', related_name='shared_clients', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
        migrations.AddField(
            model_name='invite',
            name='shared_with',
            field=models.ManyToManyField(help_text='Users with which invitee is shared', related_name='shared_invitees', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
    ]
