# Generated by Django 3.0.8 on 2021-09-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20210920_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=models.ForeignKey(blank=True, default=587, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.TimeZone'),
        ),
    ]
