# Generated by Django 3.0.8 on 2021-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20210920_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='twofa',
            field=models.BooleanField(default=False, verbose_name='Two Fator Authentication'),
        ),
    ]
