# Generated by Django 3.0.8 on 2021-09-22 14:01

import apps.users.models.enterprise
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_client_twofa'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='team_logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.users.models.enterprise.upload_user_avatar_to),
        ),
    ]
