# Generated by Django 3.0.8 on 2021-09-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0051_enterprise_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmlocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_location', to='cities_light.City', verbose_name='Firm city'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_city', to='cities_light.City', verbose_name='City'),
        ),
    ]
