# Generated by Django 3.0.8 on 2021-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20210922_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favorite_attorneys',
            field=models.ManyToManyField(help_text='Favorite attorney of client', related_name='clients', to='users.Attorney', verbose_name='favorite_attorneys'),
        ),
    ]
