# Generated by Django 3.0.8 on 2021-09-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210924_1932'),
        ('users', '0053_client_favorite_attorneys'),
    ]

    operations = [
    ]
