# Generated by Django 3.0.8 on 2021-10-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_merge_20210927_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='twofa',
        ),
        migrations.AddField(
            model_name='appuser',
            name='twofa',
            field=models.BooleanField(default=False, verbose_name='Two Fator Authentication'),
        ),
    ]
