# Generated by Django 3.0.8 on 2021-10-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20211005_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='paralegal',
            name='phone',
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=128, null=True, verbose_name='Phone'),
        ),
    ]
