# Generated by Django 3.0.8 on 2021-10-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20211005_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='contacted_clients',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='contacted_clients',
        ),
        migrations.RemoveField(
            model_name='paralegal',
            name='contacted_clients',
        ),
    ]
