# Generated by Django 3.0.8 on 2021-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20211007_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('firm', 'Firm')], default='individual', help_text='Type of client', max_length=50, verbose_name='Type of client'),
        ),
    ]
