# Generated by Django 3.0.14 on 2021-11-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_remove_invite_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='client_type',
            field=models.CharField(blank=True, choices=[('client', 'client'), ('lead', 'lead')], help_text='Type of invitee', max_length=50, null=True, verbose_name='Type of invitee'),
        ),
    ]
