# Generated by Django 3.0.14 on 2021-12-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20211116_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='onboarding',
            field=models.BooleanField(default=False, verbose_name='Onboarding process'),
        ),
    ]
