# Generated by Django 3.0.14 on 2022-01-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_appuser_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='tax_rate',
            field=models.CharField(blank=True, help_text='Tax rate', max_length=100, null=True, verbose_name='Tax rate'),
        ),
    ]
