# Generated by Django 3.0.14 on 2022-01-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_attorney_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='tax_rate',
        ),
    ]
