# Generated by Django 3.0.14 on 2022-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20220125_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
