# Generated by Django 3.0.14 on 2022-02-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20220223_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='fee_rate',
            field=models.DecimalField(decimal_places=2, default=None, help_text='How much attorney take per hour', max_digits=10, null=True, verbose_name='Fee rate'),
        ),
    ]
