# Generated by Django 3.0.14 on 2022-02-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20220223_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
