# Generated by Django 3.0.14 on 2023-12-15 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20220428_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paralegal',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='appuser',
            name='timezone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.TimeZone'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='enterprise', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
