# Generated by Django 3.0.14 on 2022-05-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20220428_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='timezone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.TimeZone'),
        ),
    ]
