# Generated by Django 3.0.8 on 2021-08-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_speciality_description'),
        ('promotion', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='users.TimeZone'),
        ),
    ]
