# Generated by Django 3.0.9 on 2020-08-21 02:01
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import model_utils.fields

import apps.forums.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_squashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='Number of posts in topic')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(verbose_name='Text of the post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='forums.Topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='first_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_post_in_topic', to='forums.Post', verbose_name='First post in topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_in_topic', to='forums.Post', verbose_name='Last post in topic'),
        ),
        migrations.CreateModel(
            name='FollowedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unread_post_count', models.PositiveIntegerField(default=0, verbose_name='Unread posts in topic')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_topics', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
                ('last_read_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_post', to='forums.Post', verbose_name='Last read post')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Follower of the Topic',
                'verbose_name_plural': 'Followers of Topics',
                'unique_together': {('topic', 'follower')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.forums.models.upload_category_icons_to, verbose_name='Icon link')),
                ('description', models.TextField(verbose_name='Description')),
                ('topic_count', models.PositiveIntegerField(default=0, verbose_name='Number of topics in category')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='Number of posts in category')),
                ('last_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.Post', verbose_name='Last post in category')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forum_categories', to='users.Speciality', verbose_name='Related speciality')),
                ('featured', models.BooleanField(default=True, verbose_name='Show on main page.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forums.Category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='Number of user posts on forum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_stats', to=settings.AUTH_USER_MODEL, verbose_name='User Statistic')),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'Users Stats',
            },
        ),
    ]
