# Generated by Django 3.0.9 on 2020-08-21 02:38
import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import ckeditor_uploader.fields
import model_utils.fields

import apps.social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_squashed_0029_attorney_sponsored'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('chat_channel', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Chat channel ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('participants', models.ManyToManyField(related_name='groupchats', related_query_name='social_groupchats', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Group Chat',
                'verbose_name_plural': 'Group Chats',
            },
        ),
        migrations.CreateModel(
            name='AttorneyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Post title', max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, help_text='Post Image', null=True, upload_to=apps.social.models.upload_attorney_post_image_to, verbose_name='Post Image')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Content of post', verbose_name='Body')),
                ('body_preview', models.TextField(help_text='Text preview of post', max_length=150, verbose_name='Preview')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='users.Attorney')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
