# Generated by Django 3.0.8 on 2021-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
    ]
