# Generated by Django 3.0.8 on 2021-08-25 20:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_groupchat_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('is_favorite',
                 models.BooleanField(default=False, verbose_name='Favorite')),
                ('appuser',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='chat_participants',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('is_favorite',
                 models.BooleanField(default=False, verbose_name='Favorite')),
                ('chat_channel',
                 models.UUIDField(default=uuid.uuid4, editable=False,
                                  unique=True,
                                  verbose_name='Chat channel ID')),
                ('participants',
                 models.ManyToManyField(
                    related_name='directchats',
                    related_query_name='social_directchats',
                    through='social.ChatParticipants',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Direct Chat',
                'verbose_name_plural': 'Direct Chats',
            },
        ),
        migrations.AddField(
            model_name='chatparticipants',
            name='directchat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chat_participants', to='social.DirectChat',
                verbose_name='User'),
        ),
    ]
