# Generated by Django 3.0.8 on 2021-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20211003_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
