# Generated by Django 3.0.8 on 2021-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_chats_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='title',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Title'
            ),
        ),
    ]
