# Generated by Django 3.0.14 on 2021-10-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_message_messageattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directchat',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='participants',
        ),
        migrations.DeleteModel(
            name='ChatParticipants',
        ),
        migrations.DeleteModel(
            name='DirectChat',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
