# Generated by Django 3.0.14 on 2021-10-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20211022_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
