# Generated by Django 3.0.14 on 2022-03-22 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0014_auto_20220110_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='participants',
            field=models.ManyToManyField(related_name='chats', related_query_name='social_chatss', through='social.SingleChatParticipants', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
