# Generated by Django 3.0.9 on 2020-08-21 02:41
from django.db import migrations


def update_forum_notification(apps, schema_editor):
    """Update `Topics I Follow Activity` and make it available for support too.
    """
    Support = apps.get_model('users', 'Support')
    NotificationType = apps.get_model('notifications', 'NotificationType')
    NotificationSetting = apps.get_model(
        'notifications', 'NotificationSetting'
    )

    notification_type = NotificationType.objects.get(runtime_tag='new_post')
    notification_type.is_for_support = True
    notification_type.save()

    # enable this notification for all existing Support users
    NotificationSetting.objects.bulk_create(
        NotificationSetting(
            notification_type=notification_type,
            user_id=s.user_id
        ) for s in Support.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial_squashed'),
        ('users', '0003_squashed_0035_auto_20200819_0730'),
    ]

    operations = [
        migrations.RunPython(
            code=update_forum_notification,
            elidable=False
        )
    ]
