# Generated by Django 3.0.8 on 2021-06-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_update_new_post_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='is_for_paralegal',
            field=models.BooleanField(default=False, help_text='Is notification type available for paralegal', verbose_name='Is for paralegal'),
        ),
    ]
