# Generated by Django 3.0.8 on 2021-06-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtype_is_for_paralegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='is_for_other',
            field=models.BooleanField(default=False, help_text='Is notification type available for other', verbose_name='Is for other'),
        ),
    ]
