# Generated by Django 3.0.8 on 2021-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_new_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
