# Generated by Django 3.0.8 on 2021-10-12 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0009_posted_matters_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='group',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='settings',
                to='notifications.NotificationGroup',
                verbose_name='Notification group'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='subscription',
            field=models.BooleanField(default=True,
                                      verbose_name='Subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsetting',
            unique_together={('user', 'group')},
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('by_email', models.BooleanField(
                     default=False,
                     help_text='Notify user by email',
                     verbose_name='Notify by email')),
                ('by_push', models.BooleanField(
                    default=False,
                    help_text='Notify user by push notification',
                    verbose_name='Notify by push notification')),
                ('user', models.OneToOneField(
                      editable=False,
                      on_delete=django.db.models.deletion.CASCADE,
                      related_name='notifications_subscription',
                      to=settings.AUTH_USER_MODEL,
                      verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='by_email',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='by_push',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='notification_type',
        ),
    ]
