# Generated by Django 3.0.14 on 2021-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notificaiton_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='by_chats',
            field=models.BooleanField(default=False, help_text='Notify user for chat', verbose_name='Notify for chat'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='by_contacts',
            field=models.BooleanField(default=False, help_text='Notify user for contact', verbose_name='Notify for contact'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='by_email',
            field=models.BooleanField(default=False, help_text='Notify user by email', verbose_name='Notify by email'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='by_forums',
            field=models.BooleanField(default=False, help_text='Notify user for forum', verbose_name='Notify for forum'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='by_matters',
            field=models.BooleanField(default=False, help_text='Notify user for matter', verbose_name='Notify for matter'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='by_push',
            field=models.BooleanField(default=False, help_text='Notify user by push notification', verbose_name='Notify by push notification'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsetting',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='NotificationSubscription',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='group',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='subscription',
        ),
    ]
