# Generated by Django 3.0.14 on 2021-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20211104_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='by_chats',
            field=models.BooleanField(default=True, help_text='Notify user for chat', verbose_name='Notify for chat'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='by_contacts',
            field=models.BooleanField(default=True, help_text='Notify user for contact', verbose_name='Notify for contact'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='by_email',
            field=models.BooleanField(default=True, help_text='Notify user by email', verbose_name='Notify by email'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='by_forums',
            field=models.BooleanField(default=True, help_text='Notify user for forum', verbose_name='Notify for forum'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='by_matters',
            field=models.BooleanField(default=True, help_text='Notify user for matter', verbose_name='Notify for matter'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='by_push',
            field=models.BooleanField(default=True, help_text='Notify user by push notification', verbose_name='Notify by push notification'),
        ),
    ]
