# Generated by Django 3.0.14 on 2021-11-10 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0016_billingitem_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdispatch',
            name='sender',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches_sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
    ]
